/**
 * Config.gs
 * ---------------------------------------------------------------------------
 * Tiller Budget Dashboard — every knob lives here.
 *
 * READ-ONLY CONTRACT
 *   Tiller owns Transactions, Categories, Balances, Balance History and AutoCat.
 *   This project reads them and never writes to them. See assertWritable_().
 */

/* ============================================================================
 * ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼   THE ONE-LINE SWITCH   ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
 *
 *   true   → the dashboard reads the generated "Mock ..." tabs
 *   false  → the dashboard reads Tiller's real tabs
 *
 *   After flipping it, run:  💰 Budget ▸ Set up / refresh everything
 *   Nothing else changes: every formula points at named ranges, and setup
 *   just re-aims those named ranges at the other set of tabs.
 * ==========================================================================*/
var USE_MOCK_DATA = true;
/* ==========================================================================*/


/** Tiller's tabs. Read-only. */
var TILLER_TABS = {
  transactions:   'Transactions',
  categories:     'Categories',
  balances:       'Balances',
  balanceHistory: 'Balance History'   // optional; used for debt-over-time
};

/** The mock mirror of Tiller's tabs, generated by MockData.gs. */
var MOCK_TABS = {
  transactions:   'Mock Transactions',
  categories:     'Mock Categories',
  balances:       'Mock Balances',
  balanceHistory: 'Mock Balance History'
};

/** Tabs this script creates and owns. Safe to wipe and rebuild. */
var TABS = {
  setup:     'Budget Setup',
  dashboard: 'Dashboard',
  flags:     'Flags',
  calc:      '_Calc',        // hidden: one normalized row per transaction
  chartData: '_ChartData'    // hidden: contiguous blocks the native charts read
};

/** Never written to, under any code path. */
var PROTECTED_TABS = [
  'Transactions', 'Categories', 'Balances', 'Balance History', 'AutoCat',
  'Transactions History', 'Categories Legacy'
];


/* ---------------------------------------------------------------------------
 * Buckets
 * -------------------------------------------------------------------------*/

/**
 * The four buckets you asked for, plus two housekeeping values:
 *   income  — auto-seeded onto every Tiller category whose Type is Income.
 *   ignore  — manual escape hatch to drop a category from every total.
 * Anything left blank is treated as unmapped and shows up on the Flags tab.
 */
var BUCKETS = ['income', 'fixed', 'variable', 'debt', 'savings', 'ignore'];

/** Buckets that make up "money out". (Savings is tracked separately.) */
var SPEND_BUCKETS = ['fixed', 'variable', 'debt'];

/** Buckets that appear in the category table, charts and Sankey. */
var VISIBLE_BUCKETS = ['fixed', 'variable', 'debt', 'savings'];


/* ---------------------------------------------------------------------------
 * Palette — Okabe–Ito, safe for deuteranopia / protanopia / tritanopia.
 * One colour per bucket, identical in every chart, every in-cell bar,
 * every sparkline and the Sankey.
 * -------------------------------------------------------------------------*/
var PALETTE = {
  income:   '#009E73',  // bluish green
  fixed:    '#0072B2',  // blue
  variable: '#E69F00',  // orange
  debt:     '#D55E00',  // vermillion
  savings:  '#56B4E9',  // sky blue
  leftover: '#CC79A7',  // reddish purple
  neutral:  '#6E7B85',
  total:    '#1F2A33'
};

/** "Over budget" / "under budget". Vermillion and bluish green read as
 *  red/green to trichromats but stay distinguishable to everyone else.
 *  Every colour cue is doubled with a ▲ / ▼ glyph so it never rides on hue alone. */
var SIGNAL = {
  badText:   '#8A3708',  badBg:   '#FCE8DC',
  goodText:  '#00614A',  goodBg:  '#DCF2EA',
  warnText:  '#8A6100',  warnBg:  '#FDF2DA',
  flatText:  '#4A555E',  flatBg:  '#F1F3F5'
};

var INK = {
  heading:  '#1F2A33',
  body:     '#2F3B44',
  muted:    '#6E7B85',
  hairline: '#D6DCE1',
  panel:    '#F7F9FA',
  card:     '#FFFFFF'
};


/* ---------------------------------------------------------------------------
 * Currency & number formats.
 * To move off USD, change the $ in these four strings and nothing else.
 * -------------------------------------------------------------------------*/
var FMT = {
  money:      '$#,##0.00',
  moneyBig:   '$#,##0',
  moneySigned:'$#,##0.00;[Red]($#,##0.00)',
  delta:      '"▲ "$#,##0;"▼ "$#,##0;"— flat"',
  overUnder:  '"▼ under by "$#,##0;"▲ OVER by "$#,##0;"— on target"',
  pct:        '0.0%',
  pctBig:     '0%',
  pctDelta:   '"▲ "0.0"pt";"▼ "0.0"pt";"— flat"',
  date:       'yyyy-mm-dd',
  text:       '@'
};


/* ---------------------------------------------------------------------------
 * Sizing
 * -------------------------------------------------------------------------*/
var LIMITS = {
  setupRows:       300,   // Budget Setup category rows (A5:A304)
  categoryRows:    60,    // Dashboard category-table rows
  barCategories:   25,    // bars in the "this month by category" chart
  debtAccounts:    8,     // series on the debt chart
  assetAccounts:   15,    // rows in the asset roll-up
  trendMonths:     12,    // window for charts 1, 2, 4 and every sparkline
  barChars:        20,    // REPT() bar width, category table
  goalBarChars:    30,    // REPT() bar width, savings goals
  calcHeadroom:    2000   // spare rows on _Calc so Tiller's daily sync can grow
};

/** Glyphs for the in-cell bars. Monospaced column font keeps them aligned. */
var BAR = { full: '█', empty: '░', over: '▶' };

/** Row/column geography of the Dashboard. Change here, everything follows. */
var DASH = {
  cardTitleRow:  4,
  cardValueRow:  5,   // merged with row 6
  cardDeltaRow:  7,
  cardSubRow:    8,
  goalHeaderRow: 10,
  goalMonthRow:  11,
  goalTotalRow:  12,
  statLabelRow:  13,
  statValueRow:  14,
  trendHeaderRow:16,
  chartRow1:     17,
  chartRow2:     34,
  tableHeaderRow:68,
  tableFirstRow: 69,
  notesRow:      131,
  /** Card k spans two columns: B:C, D:E, F:G, H:I. */
  cardCols: [[2, 3], [4, 5], [6, 7], [8, 9]]
};

/** Column widths, chosen so each big-number card is exactly 300px wide
 *  AND the category table underneath still reads well. */
var COL_WIDTHS = {
  1: 24,    // A  gutter
  2: 200,   // B  Category
  3: 100,   // C  Bucket
  4: 110,   // D  Actual
  5: 190,   // E  ▮ vs target  (REPT bar)
  6: 110,   // F  Budget
  7: 190,   // G  Over / Under
  8: 110,   // H  3-mo avg
  9: 190,   // I  vs 3-mo avg
  10: 150,  // J  Last 12 months (sparkline)
  11: 24    // K  gutter
};
